### ISSUE TITLE
Bag ( Segmentation fault (core dumped) )

### ISSUE THREAD

**Issue by yurii-kvark** [haarcuba/cpp-text-table#1]
current code work properly: 
`
TextTable t( '-', '|', '+' );
t.endOfRow();
t.setAlignment( 2, TextTable::Alignment::RIGHT );
std::cout << t;
`
**but without** 
`t.endOfRow();`
it`s make error: Segmentation fault (core dumped)

**Comment by haarcuba** [comment]
why would you want to do that? do you want support for an empty table?

**Comment by lokcito** [comment]
Hello,
I was trying in windows with devc++ and when I had ran your example it threw an error:
`   enum class Alignment { LEFT, RIGHT }; 
    }`

DevC++ output: TextTable.h	[Warning] scoped enums only available with -std=c++11 or -std=gnu++11

**Comment by haarcuba** [comment]
I see a warning, not an error.
Is working with c++11 a problem for you?

you are welcome to submit a pull request with something else.
