### ISSUE TITLE
UTF8 character support

### ISSUE THREAD

**Issue by cpp977** [haarcuba/cpp-text-table#11]
Is it desirable to support UTF8 characters in the table? Therefore one needs to properly compute the number of glyphs instead of the number of bytes because of mutlibyte glyphs appearing in UTF8 encoding.
I would have a patch but it will only work on a linux platform and only for UTF-8 encoded strings. I havent enough time to provide a platform independent implementation. Please tell me if you are interested. If so, I would prepare a pull request.

**Comment by haarcuba** [comment]
great idea. Perhaps you can make it in a way so that it's supported on linux, but not supported on other platforms?

E.G. if it's linux use a particular character type (class) if not, use the current implementation

**Comment by cpp977** [comment]
Yes sure, that is possible. I will also try to design it in a way that the code for different platforms could be added later, if someone needs it.

**Comment by haarcuba** [comment]
great! thanks!

**Comment by haarcuba** [comment]
closed by #12
