### ISSUE TITLE
segfault on empty table

### ISSUE THREAD

**Issue by MarisaKirisame** [haarcuba/cpp-text-table#15]
this following code will segfault

```
#include <iostream>

#define TEXTTABLE_ENCODE_MULTIBYTE_STRINGS
#define TEXTTABLE_USE_EN_US_UTF8

#include "TextTable.h"

int main()
{
    TextTable t( '-', '|', '+' );
    std::cout << t;
    return 0;
}
```

**Comment by haarcuba** [comment]
hi, thanks!

are you perhaps willing to suggest a fix in a pull request?

**Comment by haarcuba** [comment]
@MarisaKirisame thanks I appreciate it.

there's one small problem - when I `std::cout << emtpy_table` I get a single `+` printed, which doesn't make sense.

it should print nothing, in my opinion.

can you fix?

**Comment by MarisaKirisame** [comment]
@haarcuba yes. I am not sure what should print, so I didnt touched it.
I will change it to print empty table.

**Comment by MarisaKirisame** [comment]
@haarcuba I made the change.

**Comment by haarcuba** [comment]
@MarisaKirisame thanks again!

**Comment by MarisaKirisame** [comment]
❤️
