### ISSUE TITLE
License

### ISSUE THREAD

**Issue by friedmud** [haarcuba/cpp-text-table#2]
I'm interested in using (and possibly improving) your code here... but I can't because the license is incompatible with my project.

My project ( https://github.com/idaholab/moose ) is LGPL 2.1... and can't have GPL components in it.

Any chance you would consider changing the license to LGPL 2.1 or BSD?

**Comment by haarcuba** [comment]
I don't mind, but can I just change the license after the fact?

**Comment by haarcuba** [comment]
apparently I can. sure, no problem.

**Comment by friedmud** [comment]
Really - cool thanks!

In the meantime I had some free time over this long weekend and wanted to learn more about variadic templates anyway... so I went and implemented my own: https://github.com/friedmud/variadic_table

It only solves this for one of my use-cases though (where I know all the columns to be printed at compile time)... there is still another use-case with variable columns decided at runtime where I might still use your library.

Thanks again for responding and changing the license!
